### ISSUE TITLE
Question after installation

### ISSUE THREAD

**Issue by loisks317** [vtsuperdarn/RSTLite#2]
So I installed RST Lite and everything *looks* good, but when I try:

make_fit -new rawacf_file.rawacf > fitacf_file.fitacf

with the example rawacf file included, I get 'permission denied'. When adding sudo, I still get a permission denied. Any thoughts? 

Thanks!

**Comment by ksterne** [comment]
Without any output, I'd say there could be a couple of issues with permissions.  Do you have read permissions on the rawacf_file.rawacf?  Do you have write permissions in the directory of where you're trying to create the fitacf_file.fitacf?  Lastly, do you have executing permissions on the make_fit binary file located in `~/RSTLite/bin/`?

To check permissions in linux, use `ls -l`.  This will tell you the permissions of the file ordered by user, group, all as well as the user and group that is set for each.

**Comment by loisks317** [comment]
Ack! I should have known that. Thank you **ksterne**, that was it and things are working smoothly now (I think AJ's comments on the RSTLite install page indicate this is the 'rejoice' step)
