### ISSUE TITLE
Should label repository as deprecated

### ISSUE THREAD

**Issue by egthomas** [vtsuperdarn/RSTLite#3]
Like VTRST3.5, this repository should also probably be marked as deprecated with a link to the SuperDARN RST github repository provided (https://github.com/superdarn/rst).  Particularly since RST 4.0 is an even more stripped-down version than RSTLite (10MB vs 22MB zip archive size) with improved functionality and simplified compilation.

**Comment by ksterne** [comment]
And lo, it was deprecated (4d000b3).  Now if only we could get the same over on the sd-data-analysis repo(https://github.com/SuperDARN-DA-WG), we'd have a clear answer to the outside world on where development was going on!

**Comment by egthomas** [comment]
Unfortunately I think @jspaleta was the owner of that repository.  Not sure if he still monitors github or his old email accounts but it could be worth trying to contact him about it.

**Comment by ksterne** [comment]
@pasha-ponomarenko is in on it as well.  I've been in contact with him (https://github.com/SuperDARN-DA-WG/sd-data-analysis/issues/5) on cleaning it up but SuperDARN & apathy...
